### ISSUE TITLE
How to start local server for testing

### ISSUE THREAD

**Issue by codingwatching** [DevBobcorn/CornCraft#1]
Hi @DevBobcorn 
Thank you for this awesome project!
Could you please help me how to set up a basic server for testing this client?
Could I connect to a real server online or just download some jar server and start it? I am a newbie in this Client- Server Minecraft
Thank you!

**Comment by DevBobcorn** [comment]
Hi!
I'm really glad that you liked this project and I'd like to let more people have fun with it. However, since it is still WIP and currently going through a heavy code refactor, it might take some more time to improve this client and make it easier to use. Once these things are done, I'll write some documentations on the wiki page about how to play with this client : )

**Comment by codingwatching** [comment]
Sure! I just want to play test and try, this is awesome project so far!
I some how can connect to server but I do not have "Resource Packs" data so the game can not render 
Could you please send me zip file of running data so I can test?
Thank you so much! Keep up the great work!

**Comment by codingwatching** [comment]
Hi @DevBobcorn 
I follow all steps on readme and use resource park from Minecraft 1.16.5 but still have some warnings like this:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/85933804/191169023-706cab67-5075-4db8-b9ff-bc95861d6f23.png">

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/85933804/191169098-f5aaf11b-b02c-4fdc-86e6-69afc124cfa4.png">

**Comment by DevBobcorn** [comment]
Probably your resource pack wasn't placed at the right place, or you didn't put a <code>pack.mcmeta</code> file in the resource pack folder (forgot to mention that in <code>README</code>).
Here's a screenshot of what a resource pack folder should look like (showing a 1.16.5 vanilla resource pack):
![resource pack path](https://user-images.githubusercontent.com/49587038/191172883-2cc8576f-4468-478a-813a-2eeb5ae1cc6c.png)

**Comment by DevBobcorn** [comment]
The <code>pack.png</code> is not necessary for CornCraft, but a <code>pack.mcmeta</code> is required for CornCraft to recgonize this folder as a resource pack folder. In this file you could just write 
```json
{
  "pack": {
    "pack_format": 6,
    "description": "Blah blah blah"
  }
}
```
and it'll do the trick, the value of <code>pack_format</code> is not used by CornCraft yet, though.

**Comment by codingwatching** [comment]
@DevBobcorn Thank you so much! Could you please tear down more folders in the assets folder so I can check it correctly?
Thank you for the detailed explanation! Have a nice day!

**Comment by codingwatching** [comment]
@DevBobcorn Awesome! the pack.mcmeta does the trick!
The block selection indicator is pink on my computer, maybe it lost the material?
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/85933804/191221706-57c4d8b5-25e2-4a03-9681-d01be196cd8e.png">

Thank you so much for your great work!

**Comment by DevBobcorn** [comment]
Glad to know you got to it work! I guess I forgot to include the wireframe shader in the build files, so this material isn't working. I'll fix this soon ^._.^= ∫
