### ISSUE TITLE
Cannot support ViaVersion Backward

### ISSUE THREAD

**Issue by benda95280** [DevBobcorn/CornCraft#11]
Dear,

It seems it do not support ViaVersion Backwards (_Bukkit Plugin to work with older client version_). The client won't connect at all.
Is there a way to let the client connect ?

Regards,

**Comment by benda95280** [comment]
![image](https://github.com/DevBobcorn/CornCraft/assets/1539408/f1d198f2-b593-4c63-9d6b-2addf81c4e0c)
![image](https://github.com/DevBobcorn/CornCraft/assets/1539408/c11e62b3-b9ff-453d-b85b-2b53590ea865)

Seems really the version of the server

**Comment by DevBobcorn** [comment]
Looks like CornCraft refused to connect because it received a server version of `1.20.4`, which is not supported by default. I'll see if I can make an exception for these new servers with `ViaBackward` installed.

**Comment by Broco8Dev** [comment]
any updates? still an issue with my 1.21 viabackwards server

**Comment by DevBobcorn** [comment]
Made it possible to try to use latest supported version to attempt to connect to newer server versions. 1.20.4 paper with ViaBackwards is working now, but for 1.21+ there still some work to be done.
