### ISSUE TITLE
he type or namespace name...

### ISSUE THREAD

**Issue by mosaiyka** [DevBobcorn/CornCraft#12]
Errors:

Assets\Scripts\Rendering\Environment\Enviro3EnvironmentManager.cs(3,7): error CS0246: The type or namespace name 'Enviro' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Rendering\Environment\Enviro3EnvironmentManager.cs(9,34): error CS0246: The type or namespace name 'EnviroManager' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Rendering\Environment\Enviro3EnvironmentManager.cs(10,34): error CS0246: The type or namespace name 'EnviroWeatherType' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Rendering\Environment\Enviro3EnvironmentManager.cs(11,34): error CS0246: The type or namespace name 'EnviroWeatherType' could not be found (are you missing a using directive or an assembly reference?)

**Comment by DevBobcorn** [comment]
The project require some third party assets to build, you can either get them or replace them with something else. See [here](https://github.com/DevBobcorn/CornCraft/blob/master/Assets/Third%20Party%20Assets.md) for more info.
