### ISSUE TITLE
World.GetDimensionType not found

### ISSUE THREAD

**Issue by codingwatching** [DevBobcorn/CornCraft#14]
Hi @DevBobcorn 

I checked out the recent version and encountered this error. Could you take a look and help me find the suitable version of craftsharp-protocol? Thank you so much! Have a great day!

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/50b16b4c-fd94-405a-9de8-08f482973d4b">

**Comment by DevBobcorn** [comment]
Oh, my bad. I forgot to update the base CraftSharp package. Just a minute.

**Comment by codingwatching** [comment]
@DevBobcorn Thank you so much!
