### ISSUE TITLE
Question on place and destroy block

### ISSUE THREAD

**Issue by codingwatching** [DevBobcorn/CornCraft#17]
@DevBobcorn 
Hello, I haven’t seen the place block and destroy block features in the interaction menu X. Are these features supported yet, or do you have plans to support them soon? Thank you! Have a great day!

**Comment by DevBobcorn** [comment]
I'm thinking about implementing placing/digging blocks and interacting with entity as a "camera aiming mode", which will give you a crosshair to select the interaction target. Not sure exactly how to do that yet, but I'll work on that.

**Comment by codingwatching** [comment]
@DevBobcorn Yay! Thank you so much!
