### ISSUE TITLE
Few question about features and design

### ISSUE THREAD

**Issue by Sieluna** [DevBobcorn/CornCraft#19]
Q1: I noticed a dig logic in the `CornClientOnline`, What is the recommended timer design for this? Should this involve starting a coroutine or use a different approach?
https://github.com/DevBobcorn/CornCraft/blob/1f36bbdfbb5c0f654dc10f1ba7c29b8ba2937314/Assets/Scripts/Client/CornClientOnline.cs#L1683-L1702

Q2: How do you usually approach state management? I noticed some separation between business logic and the view in the GUI section, though it’s not entirely distinct. Are there specific guidelines or principles you like to follow for this?

**Comment by DevBobcorn** [comment]
For Q1:
Block placing/digging interactions are not really implemented yet, I was planning to do this as a part of the item action system(which also handles using tool items and weapons)

For Q2:
Most state management code concerning login and communication logic are inherited from MCC code. As for gameplay logic, currently it's not following any specific practices, but I'm considering improving the overall structure of interaction/item action system for better readability.
