### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by victorbnl** [DevBobcorn/CornCraft#3]
Are you planning on distributing binaries for the game, for instance via GitHub's release system? I'm trying to make an AUR package but building it seems rather complicated, for as far as I know it requires a Unity account and graphical Unity3D installation from the Hub.

If not, would you have any clue about how the game could be built from command line, without any sort of authentication / graphical input? I don't know much about Unity

**Comment by DevBobcorn** [comment]
Hi,
CornCraft doesn't have any releases yet since it is still in an early stage of development, so currently the only way to run this game is to build it by yourself (with Unity). Builds and releases will be available in the future when everything is ready : )
