### ISSUE TITLE
Pig Circle

### ISSUE THREAD

**Issue by AldeRoberge** [DevBobcorn/CornCraft#4]
![image](https://user-images.githubusercontent.com/4276275/222942320-6edaf6f0-3ab0-4a47-bd0c-1abd2655ba5b.png)

What is this supposed to mean? Lmao.

**Comment by AldeRoberge** [comment]
How can I fix this?

![Weird](https://user-images.githubusercontent.com/4276275/222942491-8307a18a-bd41-4088-b81e-2344c626eeda.gif)

![image](https://user-images.githubusercontent.com/4276275/222942500-58219907-4451-4574-9efa-505b8b9227db.png)

**Comment by DevBobcorn** [comment]
Guess there's still a bit problem with resource loading, I'll see if I can fix this

**Comment by DevBobcorn** [comment]
The pig circle was generated for entity testing in serverless mode, just for fun 😂
