### ISSUE TITLE
StackOverflowException Error

### ISSUE THREAD

**Issue by raid5d** [DevBobcorn/CornCraft#5]
I'm using the recommended Unity version and I really want to try this project out but no matter what I do it just throws a StackOverflowException error. I followed all the instructions in the read me and placed and named everything in the correct folders. I've spent hours using different resource packs and messing around with the vanilla_fix file. I've thrown away everything and redownloaded the project again. Nothing fixes it, the project just doesn't work. No matter what I do the StackOverflowException error pops up. My PC has more than enough memory and it seems other people in older versions of the project can run it just fine. Could you try and look around in your project please in case its a bug? Or help me fix it? Thanks!

**Comment by DevBobcorn** [comment]
Sorry for this really late reply, guess I didn't have the time to deal with this issue back then. Did you try newer versions of the game?

**Comment by DevBobcorn** [comment]
Since there's no similar issue reports in recent versions, I'll close this issue for now. Feel free to open this issue if you encounter such problem again.
