### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by EMILUS590** [DevBobcorn/CornCraft#6]
MCC_OFFLINE
MCC.SERVER_PROTOCOL
LOGIN.DATA_NOT_AVAILAVE
how to fix these errors?
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/fb999902-b01b-4897-a4ac-cc3ff4a96ab3)

**Comment by DevBobcorn** [comment]
CornCraft now uses Unity's persistent data path to store resource files and data files. On Windows, the data path is at `C:\Users\<Your Name>\AppData\LocalLow\DevBobcorn\CornCraft`.

For the time being, it is required to move the **data files** manually, just copy the whole `Extra Data` folder to that path, and they'll be properly loaded.

The **resource files** doesn't require manual operation, though. Before you join a server, the game will check if resource files for the corresponding version are present, and if not, download them automatically. The downloaded resource files are also stored at the data path mention above.

**Comment by EMILUS590** [comment]
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/43dc70c0-f426-4795-8d77-3f1e75c521ed)

what to do in this situation ? ,_,

**Comment by DevBobcorn** [comment]
That's weird, I've tested with 1.18.2 servers just now and didn't see any problem loading resources. I've also tried removing the 1.18.2 resource pack and let the game download them again, and still I didn't see the float3x3 conversion warning. So I guess you can try deleting all items in `Resource Packs` and see if the problem persists.

**Comment by DevBobcorn** [comment]
And by the way, the `vanilla_fix` resource pack is from Amulet Map Editor, you can get it here:
https://github.com/gentlegiantJGC/Minecraft-Model-Reader/tree/master/minecraft_model_reader/api/resource_pack/java/java_vanilla_fix

This resource pack is used to fix rendering for some hard-coded block models, for example, beds, shulker boxes and chests. It is not required for the game to run, so you can safely ignore the first two warnings if you don't want to add it.

**Comment by EMILUS590** [comment]
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/ff8b5482-4c34-48ed-bb21-eef32cf69b87)
Is this how it should be?

**Comment by DevBobcorn** [comment]
Probably some packages are not successfully downloaded, or maybe they are not updated to the latest version?

Here's a screenshot of 3rd-party packages used in the project, you can check if you have these in your package manager:
![Packages](https://github.com/DevBobcorn/CornCraft/assets/49587038/031972ab-2dab-4caa-a73c-f799fef4a972)

**Comment by EMILUS590** [comment]
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/58830ef7-d426-4a08-a095-e0e176a3afe2)
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/1820577c-7bb8-4171-b2b9-d9e7eafae0c1)
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/37e9e354-b64a-4b8e-bc90-5f0111052d8e)
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/12745690-8947-4875-b1bb-9738320f818e)

When I open a project, the CraftSharp resource is not downloaded. I download the CraftSharp-resource via git and it still gives me this error.

**Comment by DevBobcorn** [comment]
Did you get the CornCraft repository via git or from the zip file?

**Comment by EMILUS590** [comment]
Zip

**Comment by DevBobcorn** [comment]
Well, It's possible that the project was temporarily broken when you downloaded it. If that was the case, you'll need to pull the changes via git. If you downloaded the project as a zip file (though the download button on Github), you'll need to download the latest version again.

**Comment by EMILUS590** [comment]
via https link?

**Comment by DevBobcorn** [comment]
you can use git clone to download the project, and when there's updates, you can use git pull to apply them. It's much more convenient than downloading the zip file every time

**Comment by EMILUS590** [comment]
I'm new to using git-hub but thanks for the advice🫡

**Comment by AndrzejKebab** [comment]
bro why i get notifications for this XD i got soo spammed by this

**Comment by EMILUS590** [comment]
![image](https://github.com/DevBobcorn/CornCraft/assets/88402135/30fc6bf9-7baf-43d9-a5fa-9e148359cd94)

**Comment by EMILUS590** [comment]
cool ))))

**Comment by DevBobcorn** [comment]
> bro why i get notifications for this XD i got soo spammed by this

Sorry for the inconvenience, guess the project was on your watch list XD

**Comment by EMILUS590** [comment]
I still couldn't fix my problem ,_,

**Comment by EMILUS590** [comment]
can you please upload the files themselves in the form of a build, and in the project itself

**Comment by DevBobcorn** [comment]
The project is not ready for a release yet so I used Google Drive. The zip contains all source files and the .git folder.
Here's the link: https://drive.google.com/file/d/127CNCfx8L5fxvi2f9bvz5FWI695eAlIB/view?usp=sharing

And the data files: https://drive.google.com/file/d/1lfqLcHGlutjLlSc7sbORM1Nb9muli4GZ/view?usp=sharing

**Comment by DevBobcorn** [comment]
Also made a build here: https://drive.google.com/file/d/1buhXr6q2mMskJHoswE3UqABTOLtrGR01/view?usp=sharing

**Comment by EMILUS590** [comment]
thanks a lot
