### ISSUE TITLE
Prefab instance problem. Missing Prefab Asset: '流萤3.0 (Missing Prefab with guid: 75e2993040f85d9469c7377f3b5812d1)'

### ISSUE THREAD

**Issue by neoiw0** [DevBobcorn/CornCraft#7]
Please fix Scenes: World Offline

I assume "Scenes: World Offline" is where I start to paly it Offline, but it shows Missing Prefab Asset: '流萤3.0

**Comment by DevBobcorn** [comment]
Oh, that is a reference to a copyrighted character model which is excluded from the git repo. I'll add another model to replace it soon.

**Comment by neoiw0** [comment]
Thanks Herta

**Comment by neoiw0** [comment]
Hi, is there an offline scene that i can play minecraft without a sever?

**Comment by DevBobcorn** [comment]
Just click the button at bottom left corner on login screen and it'll take you to the offline scene.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DevBobcorn** [comment]
There isn't too much to play with on that scene, though. It was used for testing the player controller.
