### ISSUE TITLE
Data not available

### ISSUE THREAD

**Issue by benda95280** [DevBobcorn/CornCraft#8]
Hello,

I've been able build it, and when trying to join it show : Data not available.

How can i fix it ?
Thanks.

**Comment by DevBobcorn** [comment]
The data loader is still under development and will be available soon, but before that it will require some manual set up to properly load the resource and data files(including translation files). I'll leave a reply here when I complete this.

**Comment by DevBobcorn** [comment]
If you want to try it right now, you can do the data preparation manually. Just copy the whole `Extra Data` folder to `C:\Users\<Your Name>\AppData\LocalLow\DevBobcorn\CornCraft\Extra Data`, and the data should load.

**Comment by benda95280** [comment]
Just done what you said earlier, and notification are in chinese.
It seems it's not by default in english. How can i switch it ?

![image](https://github.com/DevBobcorn/CornCraft/assets/1539408/6ae6ee76-7e44-4d6a-93b0-1bb8d83f4510)

**Comment by DevBobcorn** [comment]
Oh, yes, it is currently hard-coded, you can change it here:
https://github.com/DevBobcorn/CornCraft/blob/master/Packages/com.devbobcorn.craftsharp-protocol/Runtime/Scripts/CornGlobal.cs#L26

**Comment by benda95280** [comment]
I'm stuck at : Loading blocks models.

Log:
```
Mono path[0] = 'C:/Users/Benjamin/Downloads/CornCraft-master/Build/CornCraft_Data/Managed'
Mono config path = 'C:/Users/Benjamin/Downloads/CornCraft-master/Build/MonoBleedingEdge/etc'
[Physics::Module] Initialized MultithreadedJobDispatcher with 7 workers.
Initialize engine version: 2022.3.28f1 (6bae5ce6b222)
[Subsystems] Discovering subsystems at path C:/Users/Benjamin/Downloads/CornCraft-master/Build/CornCraft_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1660 Ti (ID=0x2191)
    Vendor:   NVIDIA
    VRAM:     5966 MB
    Driver:   31.0.15.5222
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.248 seconds
- Finished resetting the current domain, in  0.003 seconds
<RI> Initializing input.
New input system (experimental) initialized
Using Windows.Gaming.Input
<RI> Initialized touch support.
UnloadTime: 1.149000 ms
Retrieving Server Info...
[vanilla-1.18.2] format: 4, description: Meow~
No resource pack found at C:/Users/Benjamin/AppData/LocalLow/DevBobcorn/CornCraft\Resource Packs\vanilla_fix
Trying to load resources from an invalid resource pack!
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.
Cannot convert to float3x3: Input string was not in a correct format.

```

**Comment by DevBobcorn** [comment]
So I checked the resource loader and found a bug when trying to download default translation file(`en_us.json`) and [fixed it](https://github.com/DevBobcorn/CornCraft/commit/fa2de0ba58cf5bc70f073ac83570f701f665a7fd), and then I tried removing all files from `Resource Packs` folder and everything still works, the resource files gets downloaded and load properly.
I did not, However, reproduce this `Cannot convert to float3x3: Input string was not in a correct format.` error, can you share a screenshot of the console to show me the stacktrace?

**Comment by DevBobcorn** [comment]
And by the way, `vanilla_fix` is not mandatory, so you can safely ignore these two lines:
> No resource pack found at C:/Users/Benjamin/AppData/LocalLow/DevBobcorn/CornCraft\Resource Packs\vanilla_fix
Trying to load resources from an invalid resource pack!

**Comment by benda95280** [comment]
> I did not, however, successfully reproduce this `Cannot convert to float3x3: Input string was not in a correct format.` error, can you share a screenshot of the console to show me the stacktrace?

How can i generate / gather this ? Not very familiar with Unity IDE.
Regards,

**Comment by DevBobcorn** [comment]
You can don't have to build it to run, you can run it in Editor by pressing the play button in `Login` scene, and then you will see log info being printed into the `Console` tab.

**Comment by DevBobcorn** [comment]
Or you can check the `Development Build` option when building the game, and then it will connect to Unity Editor when you run it. In this way you can also see runtime log info in Unity Editor's console.

**Comment by benda95280** [comment]
[Player.log](https://github.com/DevBobcorn/CornCraft/files/15369032/Player.log)
[Editor.log](https://github.com/DevBobcorn/CornCraft/files/15369033/Editor.log)

Is it what you need ?

**Comment by DevBobcorn** [comment]
Actually I want a screenshot of the console in Editor showing this error message, like this:
![Console](https://github.com/DevBobcorn/CornCraft/assets/49587038/fbe63cfe-bc5c-4065-9247-1ab3e9462c4d)
The stacktrace shown in the lower panel helps me to locate the problem.

**Comment by DevBobcorn** [comment]
After checking my code I found that this message is printed from [here](https://github.com/DevBobcorn/CraftSharp/blob/main/Runtime/Scripts/Utils/VectorUtil.cs#L69), which is called by `BlockModelLoader` or `ItemModelLoader` in resource pack parser. However this should raise warnings instead of errors, and shouldn't stop the game from running.

**Comment by DevBobcorn** [comment]
Oh I finally realized what's wrong here, it's the different number format in different `CultureInfo`s. If your system locale is French, C# uses French number format, which uses comma as the decimal separator, to parse the float value from string, and that leads to the problem here.
![Float Parse](https://github.com/DevBobcorn/CornCraft/assets/49587038/9db923cc-c97e-4b62-9a48-d254c4d9d896)

**Comment by DevBobcorn** [comment]
I'll patch this soon.

**Comment by benda95280** [comment]
Thanks !
